{% set name = "proxsuite-nlp" %}
{% set version = "0.3.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/Simple-Robotics/{{ name }}/releases/download/v{{ version }}/{{ name }}-{{ version }}.tar.gz
  sha256: 6f5c2dbdd45277f5c1c7162e6b68ccadc1234c538bd22bb24d46c3f48b3986aa

build:
  number: 1
  run_exports:
    - {{ pin_subpackage(name, max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake
    - clang  # [win]
    - ninja  # [win]
    - make  # [not win]
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
  host:
    - eigen
    - eigenpy
    - libboost-devel
    - libboost-python-devel
    - fmt
    - pinocchio
    - python
    - numpy
    - benchmark
    - example-robot-data
  run:
    - eigen
    - eigenpy
    - python
    - {{ pin_compatible('numpy') }}
    - matplotlib-base
    - typed-argument-parser
    - tqdm
    - meshcat-python

test:
  commands:
    - test -f $PREFIX/lib/lib{{ name }}${SHLIB_EXT}  # [not win]
    - if not exist %LIBRARY_PREFIX%\bin\{{ name }}.dll exit 1  # [win]
  imports:
    - proxsuite_nlp
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/simple-robotics/proxsuite-nlp
  summary: A primal-dual augmented Lagrangian solver for nonlinear programming on manifolds.
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE
  dev_url: https://github.com/simple-robotics/proxsuite-nlp

extra:
  recipe-maintainers:
    - olivier-roussel
    - jcarpent
    - jorisv
    - ManifoldFR
