{% set name = "proxsuite-nlp" %}
{% set version = "0.6.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/Simple-Robotics/{{ name }}/releases/download/v{{ version }}/{{ name }}-{{ version }}.tar.gz
  sha256: 3ed3b52e23e0ce77ea4c4a612974cb02dae4e2b61b7d52c89287c031b9b79ff0

build:
  number: 0
  run_exports:
    - {{ pin_subpackage(name, max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
    - cmake
    - clang  # [win]
    - ninja  # [win]
    - make  # [not win]
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
  host:
    - eigen
    - eigenpy
    - libboost-devel
    - libboost-python-devel
    - fmt
    - pinocchio
    - python
    - numpy
    - benchmark
    - example-robot-data
  run:
    - eigen
    - eigenpy
    - python
    - {{ pin_compatible('numpy') }}
    - matplotlib-base
    - typed-argument-parser
    - tqdm
    - meshcat-python

test:
  commands:
    - test -f $PREFIX/lib/lib{{ name }}${SHLIB_EXT}  # [not win]
    - if not exist %LIBRARY_PREFIX%\bin\{{ name }}.dll exit 1  # [win]
  imports:
    - proxsuite_nlp

about:
  home: https://github.com/simple-robotics/proxsuite-nlp
  summary: A primal-dual augmented Lagrangian solver for nonlinear programming on manifolds.
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE
  dev_url: https://github.com/simple-robotics/proxsuite-nlp

extra:
  recipe-maintainers:
    - olivier-roussel
    - jcarpent
    - jorisv
    - ManifoldFR
