{% set name = "proxsuite-nlp" %}
{% set version = "0.11.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/Simple-Robotics/{{ name }}/releases/download/v{{ version }}/{{ name }}-{{ version }}.tar.gz
  sha256: 9dcb750377c2b17d0a277ef61ae9fb6b12d466a50215dbcb59b79f0f36c4f2c3

build:
  number: 5
  run_exports:
    - {{ pin_subpackage(name, max_pin='x.x.x') }}

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
    - cmake
    - clang  # [win]
    - ninja  # [win]
    - make  # [not win]
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
  host:
    - eigen
    - eigenpy
    - libboost-devel
    - libboost-python-devel
    - fmt
    - pinocchio
    - python
    # On Windows, Numpy 2.0 don't allow to export the PY_ARRAY_UNIQUE_SYMBOL.
    # This has been fixed in Numpy 2.1.
    - numpy >=2.1      # [win and py>=310]
    # Unfortunatly, Numpy 2.1 is not distributed with Python 3.9.
    # We are forced to use Numpy 1 in this case.
    - numpy >=1.19,<2  # [win and py<310]
    - numpy            # [not win]
  run:
    - eigen
    - eigenpy
    - python
    - matplotlib-base
    - numpy >=2.1                    # [win and py>=310]
    - {{ pin_compatible('numpy') }}  # [win and py<310]

test:
  commands:
    - test -f $PREFIX/lib/lib{{ name }}${SHLIB_EXT}  # [not win]
    - if not exist %LIBRARY_PREFIX%\bin\{{ name }}.dll exit 1  # [win]
  imports:
    - proxsuite_nlp

about:
  home: https://github.com/simple-robotics/proxsuite-nlp
  summary: A primal-dual augmented Lagrangian solver for nonlinear programming on manifolds.
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE
  dev_url: https://github.com/simple-robotics/proxsuite-nlp

extra:
  recipe-maintainers:
    - olivier-roussel
    - jcarpent
    - jorisv
    - ManifoldFR
